// flow-typed signature: 362a8049bff2e99c9a139e4eac57010e
// flow-typed version: <<STUB>>/eslint-config-gemcook_v^1.0.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-gemcook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-gemcook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-gemcook/index' {
  declare module.exports: $Exports<'eslint-config-gemcook'>;
}
declare module 'eslint-config-gemcook/index.js' {
  declare module.exports: $Exports<'eslint-config-gemcook'>;
}
